server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: docker
eureka:
  client:
    service-url:
      defaultZone: http://eurekaServer:8761/eureka

